#!/usr/bin/env bun
import { readdirSync, readFileSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { join, posix, relative } from 'node:path';

const DIST_DIR = join(import.meta.dir, '..', 'src', 'web', 'dist');
const OUT_FILE = join(import.meta.dir, '..', 'src', 'web', 'embedded-assets.generated.ts');

// Files we treat as text (everything else gets base64-encoded).
const TEXT_EXTS = new Set(['.html', '.js', '.mjs', '.css', '.json', '.svg', '.txt', '.md']);

interface Entry {
  urlPath: string;
  encoding: 'text' | 'base64';
  content: string;
}

function walk(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      out.push(...walk(full, base));
    } else {
      out.push(full);
    }
  }
  return out;
}

function entryFor(absPath: string): Entry {
  const rel = relative(DIST_DIR, absPath);
  // URL paths use forward slashes regardless of host OS.
  const urlPath = '/' + rel.split(/[/\\]/).join('/');
  const ext = (urlPath.match(/\.[^.]+$/)?.[0] ?? '').toLowerCase();
  if (TEXT_EXTS.has(ext)) {
    return { urlPath, encoding: 'text', content: readFileSync(absPath, 'utf8') };
  }
  return { urlPath, encoding: 'base64', content: readFileSync(absPath).toString('base64') };
}

function escapeForBackticks(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function main(): void {
  if (!existsSync(DIST_DIR)) {
    console.error(`embed-assets: ${DIST_DIR} does not exist. Run 'bun run build:web' first.`);
    process.exit(1);
  }

  const files = walk(DIST_DIR).map(entryFor);
  files.sort((a, b) => a.urlPath.localeCompare(b.urlPath));

  const lines: string[] = [
    '// AUTO-GENERATED by scripts/embed-assets.ts. Do not edit.',
    '// Regenerated on every `bun run build:web && bun run scripts/embed-assets.ts`.',
    '',
    'export interface EmbeddedAsset {',
    "  encoding: 'text' | 'base64';",
    '  content: string;',
    '}',
    '',
    'export const EMBEDDED_ASSETS: Record<string, EmbeddedAsset> = {',
  ];
  for (const f of files) {
    lines.push(`  ${JSON.stringify(f.urlPath)}: { encoding: ${JSON.stringify(f.encoding)}, content: \`${escapeForBackticks(f.content)}\` },`);
  }
  lines.push('};');
  lines.push('');

  writeFileSync(OUT_FILE, lines.join('\n'), 'utf8');
  console.log(`embed-assets: wrote ${files.length} files to ${posix.relative(process.cwd(), OUT_FILE)}`);
}

main();
